default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV['DB_POOL'] || 2 %>
  reaping_frequency: <%= ENV['DB_REAPING_FREQUENCY'] || 30 %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
